## 3. MACHINE LEARNING FOR CLASSIFICATION

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

pd.set_option('display.max_columns', None)

df = pd.read_csv('telco_customer_churn.csv', sep=',')

print(f'columns: {df.shape[1]}\nrows: {df.shape[0]}')
display(df.head(2).T)
display(df.describe().T)
##display(df.dtypes)

columns: 21
rows: 7043

                                 0             1
customerID              7590-VHVEG    5575-GNVDE
gender                      Female          Male
SeniorCitizen                    0             0
Partner                        Yes            No
Dependents                      No            No
tenure                           1            34
PhoneService                    No           Yes
MultipleLines     No phone service            No
InternetService                DSL           DSL
OnlineSecurity                  No           Yes
OnlineBackup                   Yes            No
DeviceProtection                No           Yes
TechSupport                     No            No
StreamingTV                     No            No
StreamingMovies                 No            No
Contract            Month-to-month      One year
PaperlessBilling               Yes            No
PaymentMethod     Electronic check  Mailed check
MonthlyCharges               29.85         56.95
TotalCharges                 29.85        1889.5
Churn                           No            No

,count,mean,std,min,25%,50%,75%,max
SeniorCitizen,7043.0,0.162147,0.368612,0.00,0.0,0.00,0.00,1.00
tenure,7043.0,32.371149,24.559481,0.00,9.0,29.00,55.00,72.00
MonthlyCharges,7043.0,64.761692,30.090047,18.25,35.5,70.35,89.85,118.75

### 3.2 DATA PREPARATION

In [12]:
df.columns = df.columns.str.upper().str.replace(' ', '_')
string_list = list(df.dtypes[df.dtypes == 'str'].index)

for col in string_list:
    df[col] = df[col].str.lower().str.replace(' ', '_').str.replace('-', '_')

# column example with string value that should be numeric
# let fix it by replacing with 0 and then convert to numeric
display(df[df.index == 488].T)

df['TOTALCHARGES'] = pd.to_numeric(df['TOTALCHARGES'].replace('_', '0'), errors='coerce')
df['MONTHLYCHARGES'] = pd.to_numeric(df['MONTHLYCHARGES'].replace('_', '0'), errors='coerce')

#df['CHURN'] = df['CHURN'].map({'yes': 1, 'no': 0})
df['CHURN'] = (df['CHURN'] == 'yes').astype(int)

                                        488
CUSTOMERID                       4472_lvygi
GENDER                               female
SENIORCITIZEN                             0
PARTNER                                 yes
DEPENDENTS                              yes
TENURE                                    0
PHONESERVICE                             no
MULTIPLELINES              no_phone_service
INTERNETSERVICE                         dsl
ONLINESECURITY                          yes
ONLINEBACKUP                             no
DEVICEPROTECTION                        yes
TECHSUPPORT                             yes
STREAMINGTV                             yes
STREAMINGMOVIES                          no
CONTRACT                           two_year
PAPERLESSBILLING                        yes
PAYMENTMETHOD     bank_transfer_(automatic)
MONTHLYCHARGES                        52.55
TOTALCHARGES                              _
CHURN                                    no

In [19]:
# split the data into 80% train, 20% test, 20% of the train will be used as validation
# 20% of 80% is 16% of the total data
# so we use 20%/80% = 25% of the train data as validation
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train['CHURN']
y_val = df_val['CHURN']
y_test = df_test['CHURN']

X_train = df_train.drop(columns=['CHURN'])
X_val = df_val.drop(columns=['CHURN'])
X_test = df_test.drop(columns=['CHURN'])

print(f'train: {len(df_train)}\nvalidation: {len(df_val)}\ntest: {len(df_test)}')
display((y_train.value_counts(normalize=True)*100).round(2))

train: 4225
validation: 1409
test: 1409

CHURN
0    73.14
1    26.86
Name: proportion, dtype: float64

In [39]:
categorical_columns = list(X_train.dtypes[X_train.dtypes == 'str'].index)
numerical_columns = list(X_train.dtypes[X_train.dtypes != 'str'].index)

display(X_train[numerical_columns].head(2).T)
display(X_train[categorical_columns].head(2).T)

                      0        1
SENIORCITIZEN      0.00     0.00
TENURE            72.00    10.00
MONTHLYCHARGES   115.50    95.25
TOTALCHARGES    8425.15  1021.55

                                 0                 1
CUSTOMERID              8015_ihcgw        1960_uycnn
GENDER                      female              male
PARTNER                        yes                no
DEPENDENTS                     yes                no
PHONESERVICE                   yes               yes
MULTIPLELINES                  yes               yes
INTERNETSERVICE        fiber_optic       fiber_optic
ONLINESECURITY                 yes                no
ONLINEBACKUP                   yes               yes
DEVICEPROTECTION               yes               yes
TECHSUPPORT                    yes                no
STREAMINGTV                    yes                no
STREAMINGMOVIES                yes               yes
CONTRACT                  two_year    month_to_month
PAPERLESSBILLING               yes               yes
PAYMENTMETHOD     electronic_check  electronic_check